"""empty message

Revision ID: 4d0a6c1713c6
Revises: dda1bb26ee20
Create Date: 2016-02-21 13:50:55.149961

"""

# revision identifiers, used by Alembic.
revision = '4d0a6c1713c6'
down_revision = 'dda1bb26ee20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_2', table_name='movies')
    op.drop_index('name_3', table_name='movies')
    op.drop_index('name_4', table_name='movies')
    op.drop_index('name_5', table_name='movies')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name_5', 'movies', ['name'], unique=False)
    op.create_index('name_4', 'movies', ['name'], unique=True)
    op.create_index('name_3', 'movies', ['name'], unique=False)
    op.create_index('name_2', 'movies', ['name'], unique=False)
    ### end Alembic commands ###
