"""empty message

Revision ID: 8e451bd41d13
Revises: None
Create Date: 2016-02-16 22:05:02.474598

"""

# revision identifiers, used by Alembic.
revision = '8e451bd41d13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=False)
    op.create_index(op.f('ix_movies_origin'), 'movies', ['origin'], unique=False)
    op.create_index(op.f('ix_movies_type'), 'movies', ['type'], unique=False)
    op.create_index(op.f('ix_movies_url'), 'movies', ['url'], unique=False)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_url'), table_name='movies')
    op.drop_index(op.f('ix_movies_type'), table_name='movies')
    op.drop_index(op.f('ix_movies_origin'), table_name='movies')
    op.drop_index(op.f('ix_movies_name'), table_name='movies')
    ### end Alembic commands ###
