"""empty message

Revision ID: 90a3c66c522f
Revises: 8e451bd41d13
Create Date: 2016-02-16 22:19:29.523035

"""

# revision identifiers, used by Alembic.
revision = '90a3c66c522f'
down_revision = '8e451bd41d13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('added_by_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies', 'users', ['added_by_user'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_column('movies', 'added_by_user')
    ### end Alembic commands ###
