"""empty message

Revision ID: addc6e40cee6
Revises: b7a7e77f0226
Create Date: 2016-02-20 13:49:16.217050

"""

# revision identifiers, used by Alembic.
revision = 'addc6e40cee6'
down_revision = 'b7a7e77f0226'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('seen_where', sa.String(length=4), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'seen_where')
    ### end Alembic commands ###
