"""empty message

Revision ID: b7a7e77f0226
Revises: f44e370dbebc
Create Date: 2016-02-20 13:47:39.324341

"""

# revision identifiers, used by Alembic.
revision = 'b7a7e77f0226'
down_revision = 'f44e370dbebc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marks', sa.Column('seen_when', sa.Date(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marks', 'seen_when')
    ### end Alembic commands ###
