"""empty message

Revision ID: c6f0b1cff988
Revises: 06472926c257
Create Date: 2016-03-11 18:12:07.663326

"""

# revision identifiers, used by Alembic.
revision = 'c6f0b1cff988'
down_revision = '06472926c257'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_movies_release_date'), 'movies', ['release_date'], unique=False)
    op.drop_index('ix_movies_year', table_name='movies')
    op.drop_column('movies', 'year')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('year', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_movies_year', 'movies', ['year'], unique=False)
    op.drop_index(op.f('ix_movies_release_date'), table_name='movies')
    op.drop_column('movies', 'release_date')
    ### end Alembic commands ###
