"""empty message

Revision ID: d19230f9ce03
Revises: 4d0a6c1713c6
Create Date: 2016-02-21 14:17:53.788304

"""

# revision identifiers, used by Alembic.
revision = 'd19230f9ce03'
down_revision = '4d0a6c1713c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'movies', 'origins', ['origin'], ['id'])
    op.create_foreign_key(None, 'movies', 'types', ['type'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_constraint(None, 'movies', type_='foreignkey')
    ### end Alembic commands ###
