"""empty message

Revision ID: dda1bb26ee20
Revises: 0f7a85013413
Create Date: 2016-02-21 13:40:02.116442

"""

# revision identifiers, used by Alembic.
revision = 'dda1bb26ee20'
down_revision = '0f7a85013413'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_name', table_name='movies')
    op.create_index(op.f('ix_movies_name'), 'movies', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_name'), table_name='movies')
    op.create_index('ix_movies_name', 'movies', ['name'], unique=False)
    ### end Alembic commands ###
